# Ce fichier sera fourni par l'application qui utilise le framework
# app.package=ton.package.controllers
# annotation.controller=sharon.sprintmvc.annotation.Controller
# annotation.mapping=sharon.sprintmvc.annotation.URLMapping